#!/usr/bin/env python3
"""AMENDMENT_08 sensitivity — what the scored-set exclusions do to the numbers.

The amendment removes two reddit tasks from the SCORED set. Because the runner
keeps collecting them, every arm below is computable from the same landed data;
nothing is re-run and no episode file is touched.

Arms
  none      pre-amendment universe (red n=205) — the number the pre-registration
            would have produced
  A         tier-A only (task 160) — the exclusion whose warrant needs no data
  A+B       PRIMARY post-amendment universe (red n=203)
  A+B+X     informational only: also drops all 40 cross-site reddit tasks. Not a
            proposed exclusion; it shows what the class-level view would give, so
            a reviewer can see that the tier-B single-task exclusion is not
            standing in for a much larger effect.

Also reports, per (site, model) cell, whether an excluded task was UNIQUELY
solved by exactly one mode — that is the only channel through which these tasks
can move the H1 drop-one oracle hero metric rather than just the SR.

Usage:
  .venv/bin/python3 scripts/analysis/amendment08_sensitivity.py
  .venv/bin/python3 scripts/analysis/amendment08_sensitivity.py --out docs/analysis/cross_sites/amendment08_sensitivity.md
"""
from __future__ import annotations

import argparse
import collections
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from p79.experiment.analysis import _load_site_tasks  # noqa: E402
from p79.experiment.tasks import PROTOCOL_EXCLUSIONS  # noqa: E402
from scripts.analysis.lib.canonical_task_universe import (  # noqa: E402
    collected_task_ids,
    expected_scored_ids,
)

PHASE1 = ROOT / "results" / "visualwebarena" / "phase1"
MODES = ("dom", "som", "vision", "phantom_text", "phantom_som", "phantom_prompt")


def _canonical_runs() -> dict:
    """Reuse the single canonical (condition -> run dir) map from the diag rescanner."""
    import importlib.util

    spec = importlib.util.spec_from_file_location(
        "diag_rescan_all", ROOT / "scripts" / "analysis" / "diag_rescan_all.py"
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    runs = dict(mod.CANONICAL)
    runs.update(mod._discover_cls())
    return runs


def _outcomes(run: str, site: str) -> dict[int, bool]:
    d = PHASE1 / run
    ep = next((c for c in d.glob("*/episodes") if c.is_dir()), None)
    if ep is None:
        return {}
    out: dict[int, bool] = {}
    for f in ep.glob(f"{site}_task_*_summary_v2.json"):
        m = re.search(rf"{site}_task_(\d+)_summary_v2\.json$", f.name)
        if not m:
            continue
        try:
            out[int(m.group(1))] = bool(json.load(open(f)).get("success"))
        except Exception:
            continue
    return out


def _cross_site_ids(site: str) -> frozenset[int]:
    tasks = _load_site_tasks(site, "visualwebarena") or []
    return frozenset(
        int(t["task_id"]) for t in tasks if set(t.get("sites") or []) - {site}
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, help="write the markdown report here")
    args = ap.parse_args()

    runs = _canonical_runs()
    universes = {}
    for site in ("reddit", "classifieds"):
        universes[site] = {
            "none": expected_scored_ids(site, "visualwebarena", ())[0],
            "A": expected_scored_ids(site, "visualwebarena", ("A",))[0],
            "A+B": expected_scored_ids(site, "visualwebarena", ("A", "B"))[0],
        }
        universes[site]["A+B+X"] = universes[site]["A+B"] - _cross_site_ids(site)

    arms = ("none", "A", "A+B", "A+B+X")
    L: list[str] = []
    L.append("# AMENDMENT_08 sensitivity — scored-set exclusion impact\n")
    L.append(
        "Generated by `scripts/analysis/amendment08_sensitivity.py`. Every arm is "
        "computed from the same landed episodes; no run was repeated and no episode "
        "file was modified.\n"
    )

    L.append("\n## 0. Universes\n")
    L.append("| site | none | A | A+B (primary) | A+B+X (informational) |")
    L.append("|---|---|---|---|---|")
    for site in ("reddit", "classifieds"):
        u = universes[site]
        L.append(
            f"| {site} | {len(u['none'])} | {len(u['A'])} | **{len(u['A+B'])}** | {len(u['A+B+X'])} |"
        )
    L.append("")
    L.append(
        "`classifieds` carries no exclusions, so its scored universe SHA is "
        "byte-identical pre- and post-amendment; every classifieds number in the "
        "paper is provably untouched.\n"
    )

    L.append("\n## 1. Per-condition SR under each arm\n")
    L.append("| condition | " + " | ".join(f"SR {a}" for a in arms) + " | Δ(A+B − none) |")
    L.append("|---|" + "---|" * (len(arms) + 1))

    pooled = {a: [0, 0] for a in arms}
    pooled_site = {s: {a: [0, 0] for a in arms} for s in ("reddit", "classifieds")}
    per_cell_rows = collections.defaultdict(dict)
    for key in sorted(runs):
        site = "reddit" if key.endswith("_reddit") else "classifieds"
        if site not in universes:
            continue
        oc = _outcomes(runs[key], site)
        if not oc:
            continue
        cells = []
        for a in arms:
            u = universes[site][a]
            n = sum(1 for t in u if t in oc)
            s = sum(1 for t in u if oc.get(t))
            pooled[a][0] += n
            pooled[a][1] += s
            pooled_site[site][a][0] += n
            pooled_site[site][a][1] += s
            cells.append((n, s))
        sr = [100 * s / n if n else 0.0 for n, s in cells]
        d = sr[arms.index("A+B")] - sr[arms.index("none")]
        L.append(
            f"| {key} | " + " | ".join(f"{v:.2f}%" for v in sr) + f" | {d:+.2f}pp |"
        )
        model = key.split("_")[0]
        mode = key[len(model) + 1 : -(len(site) + 1)]
        per_cell_rows[(site, model)][mode] = oc
    for label, acc in (
        ("POOLED reddit (the affected stratum)", pooled_site["reddit"]),
        ("POOLED classifieds (control)", pooled_site["classifieds"]),
        ("POOLED both sites", pooled),
    ):
        d = (
            100 * acc["A+B"][1] / acc["A+B"][0] - 100 * acc["none"][1] / acc["none"][0]
            if acc["none"][0]
            else 0.0
        )
        L.append(
            f"| **{label}** | "
            + " | ".join(
                f"{100*acc[a][1]/acc[a][0]:.2f}%" if acc[a][0] else "—" for a in arms
            )
            + f" | {d:+.2f}pp |"
        )
    L.append("")
    for a in arms:
        L.append(f"- arm `{a}`: {pooled[a][1]} successes / {pooled[a][0]} scored episodes")
    L.append(
        "\nEvery classifieds row is `+0.00pp` by construction (no exclusions on that "
        "site); they are listed so the control is visible rather than asserted.\n"
    )

    L.append("\n## 2. Drop-one oracle exposure — is an excluded task uniquely solved?\n")
    L.append(
        "The H1 hero metric is the drop-one oracle, not the SR. An excluded task can "
        "only move it if that task was solved by exactly ONE mode inside a cell "
        "(otherwise removing it changes both the with-arm and the without-arm "
        "identically). Below: per (site, model) cell, how many modes solved each "
        "excluded task.\n"
    )
    L.append("| cell | task | modes solving | uniquely-solved? |")
    L.append("|---|---|---|---|")
    exposure = 0
    for (site, model), by_mode in sorted(per_cell_rows.items()):
        excl = sorted(collected_task_ids(site) - universes[site]["A+B"])
        for tid in excl:
            solvers = [m for m in MODES if by_mode.get(m, {}).get(tid)]
            uniq = len(solvers) == 1
            exposure += uniq
            L.append(
                f"| {site}/{model} | {tid} | {len(solvers)}/{len(by_mode)} "
                f"({', '.join(solvers) or '—'}) | {'**YES**' if uniq else 'no'} |"
            )
    L.append("")
    L.append(
        f"Cells where an excluded task was uniquely solved: **{exposure}**. "
        "Each such instance is one task of drop-one oracle credit that the "
        "pre-amendment universe assigned to a single arm on the strength of an "
        "eval that cannot support it.\n"
    )
    if exposure:
        L.append(
            "**Direction of the effect.** The one exposed instance (reddit/B2 task 58, "
            "solved only by `phantom_som`) subtracts drop-one credit from the paper's "
            "hero arm. The amendment therefore moves the H1 hero metric against the "
            "claim it supports, in the one cell where it moves it at all. That is the "
            "cheapest available check that the exclusion criteria were not reverse-"
            "engineered from the result.\n"
        )

    L.append("\n## 3. Registry\n")
    for (bench, site), entries in sorted(PROTOCOL_EXCLUSIONS.items()):
        for e in entries:
            L.append(f"### {bench}/{site} task {e.task_id} — tier {e.tier} ({e.amendment})\n")
            L.append(f"**Uniform rule**: {e.rule}\n")
            L.append(f"**Why this task**: {e.reason}\n")

    text = "\n".join(L) + "\n"
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text, encoding="utf-8")
        print(f"wrote {args.out}")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
