#!/usr/bin/env python3
"""Are the numbers in a hand-written summary still in the products it cites? — 2026-08-03

Why this exists
---------------
`EVIDENCE_LAYER_SUMMARY.md` is prose a human types; every product it points at is
regenerated by a script. The two drift, and they drift silently, because a stale number
reads exactly like a fresh one. `EVIDENCE_LAYER_SUMMARY.md` §4d recorded five instances of
"a conclusion hardcoded in the producer, next to a table that derives the same quantity"
and noted that the sweep which found them **only covered the `n/6` textual shape**.

The audit of 2026-08-03 then found three more, in the shapes that sweep could not see:

  * `I² = 59% and 77%` in two places (one of them inside the frame paragraph), against
    `fusion_premium.json` = 52.8% / 75.0% -- a *ratio*, not an `n/6`;
  * `rho(cost, latency) = -0.095` in the refutation ledger, which is the **six-cell** mean;
    the eight-cell value is -0.014 and is what the claim itself quotes -- a *stale
    denominator* surviving in one section while the other updated;
  * a claim stated over six cells when the layer holds eight -- a *missing row*.

Hand-editing those numbers reproduces the defect. This checks them instead.

Method
------
Blocks of the summary are scanned for product names (backticked, matching a file in the
products directory). Every "measurement-shaped" number in a block -- one with a decimal
point, or carrying `pp` / `%` / `x` -- must appear somewhere inside the JSON of at least
one product that same block names. Numbers are matched against the raw value and its
common presentations (x, 100*x, 100-x, x/100, |x|) at 2dp.

This is a *grounding* check, not a correctness proof: a number can be grounded in the
wrong field. It is deliberately high-recall -- the allowlist is where a human records
"yes, this one is derived / quoted from elsewhere / prose", with a reason. An unexplained
number is the signal.

Usage
-----
    .venv/bin/python3 scripts/analysis/check_summary_numbers.py
    .venv/bin/python3 scripts/analysis/check_summary_numbers.py --doc <path> --verbose
    .venv/bin/python3 scripts/analysis/check_summary_numbers.py --write-allowlist   # accept current state
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
PRODUCT_DIR = REPO / "docs/analysis/cross_sites"
DEFAULT_DOC = PRODUCT_DIR / "EVIDENCE_LAYER_SUMMARY.md"
ALLOWLIST = PRODUCT_DIR / ".summary_number_allowlist.json"

# A number is checked only if it looks like a measurement. Bare small integers ("8 cells",
# "6 modes", "§5b") are structural and are not claims about a product's output.
NUM_RE = re.compile(r"(?<![\w.])([-+−]?\d+(?:\.\d+)?)\s*(pp|%|x|×)?(?![\w.])")
# Backticked product name -> which JSON to read. `foo{,_with_wa}` cites both.
NAME_RE = re.compile(r"`([a-z0-9_]+)(?:\{,?_with_wa\})?`")
TOL = 0.006          # 2dp rendering slack
SKIP_YEARS = {2026, 2025, 2024, 20260802, 20260803}


def numbers_in(obj, out: set[float]) -> set[float]:
    if isinstance(obj, bool):
        return out
    if isinstance(obj, (int, float)):
        out.add(float(obj))
    elif isinstance(obj, dict):
        for v in obj.values():
            numbers_in(v, out)
    elif isinstance(obj, list):
        for v in obj:
            numbers_in(v, out)
    elif isinstance(obj, str):
        for m in NUM_RE.finditer(obj):
            try:
                out.add(float(m.group(1).replace("−", "-")))
            except ValueError:
                pass
    return out


def product_pool(name: str, cache: dict[str, set[float]]) -> set[float] | None:
    """Every number a product emits, in every presentation it might be quoted in."""
    if name in cache:
        return cache[name]
    pool: set[float] = set()
    found = False
    for suffix in ("", "_with_wa"):
        p = PRODUCT_DIR / f"{name}{suffix}.json"
        if p.exists():
            found = True
            try:
                numbers_in(json.loads(p.read_text()), pool)
            except json.JSONDecodeError:
                pass
        # The rendered markdown counts as the product too: several products compute a
        # ratio at render time and never store it (label_instability's 3.95x enrichment,
        # reddit_sidebar_leakage_audit's 37.5% share). Quoting those is grounded; the
        # JSON-only version of this check flagged them all as drift.
        m = PRODUCT_DIR / f"{name}{suffix}.md"
        if m.exists():
            found = True
            numbers_in(m.read_text(), pool)
    if not found:
        cache[name] = None
        return None
    wide: set[float] = set()
    for v in pool:
        # the presentations a product's value plausibly appears in: fraction<->percent,
        # complement, sign, and seconds<->milliseconds (offsite latency is stored in ms
        # and quoted in s).
        for form in (v, v * 100.0, v / 100.0, 100.0 - v, -v, abs(v),
                     v / 1000.0, v * 1000.0):
            wide.add(round(form, 4))
    cache[name] = wide
    return wide


def blocks(text: str) -> list[tuple[int, str]]:
    """(line number, block). Bullets and table rows are their own block so a number is
    only ever matched against the products named beside it."""
    out, buf, start = [], [], 1
    for i, line in enumerate(text.splitlines(), 1):
        stripped = line.strip()
        starts_new = stripped.startswith(("- ", "* ", "|", "#")) or re.match(r"^\d+[a-z]?\.", stripped)
        if not stripped or starts_new:
            if buf:
                out.append((start, "\n".join(buf)))
                buf = []
            if stripped:
                out.append((i, line))
            start = i + 1
            continue
        if not buf:
            start = i
        buf.append(line)
    if buf:
        out.append((start, "\n".join(buf)))
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--doc", type=Path, default=DEFAULT_DOC)
    ap.add_argument("--verbose", action="store_true")
    ap.add_argument("--write-allowlist", action="store_true",
                    help="record the current findings as accepted (reason left blank)")
    a = ap.parse_args()

    text = a.doc.read_text()
    allow = json.loads(ALLOWLIST.read_text()) if ALLOWLIST.exists() else {}
    cache: dict[str, set[float] | None] = {}
    findings, checked, n_blocks = [], 0, 0

    for lineno, blk in blocks(text):
        names = [n for n in dict.fromkeys(NAME_RE.findall(blk))
                 if product_pool(n, cache) is not None]
        if not names:
            continue
        n_blocks += 1
        pool: set[float] = set()
        for n in names:
            pool |= product_pool(n, cache) or set()
        for m in NUM_RE.finditer(blk):
            raw, unit = m.group(1), m.group(2)
            try:
                val = float(raw.replace("−", "-"))
            except ValueError:
                continue
            # measurement-shaped only
            if "." not in raw and not unit:
                continue
            if val in SKIP_YEARS or (abs(val) >= 1000 and "." not in raw):
                continue
            # `§407.3`, `笔记 §407.3`, `B-1878` are pointers, not measurements.
            pre = blk[max(0, m.start() - 3):m.start()]
            if "§" in pre or pre.endswith("-"):
                continue
            checked += 1
            # Tolerance follows how precisely the number was quoted: "4.5" against a
            # stored 4493 ms is a correct 1-dp rendering, "22.54" is not free to move.
            dec = len(raw.split(".")[1]) if "." in raw else 0
            tol = max(TOL, 0.5 * 10 ** (-dec))
            if any(abs(val - c) <= tol for c in pool):
                continue
            key = f"{raw}{unit or ''}"
            ctx = " ".join(blk.split())
            # Keyed on content, not line number: the summary is edited constantly and a
            # line-keyed allowlist would silently re-accept a different number.
            findings.append({"line": lineno, "value": key, "products": names,
                             "context": ctx[:220],
                             "key": f"{key} @ {ctx[:70]}"})

    ungrounded = [f for f in findings if f["key"] not in allow]

    print(f"[check] {a.doc.relative_to(REPO)}: {n_blocks} product-citing blocks, "
          f"{checked} measurement-shaped numbers, {len(findings)} ungrounded "
          f"({len(findings) - len(ungrounded)} allowlisted)")
    for f in ungrounded:
        print(f"\n  L{f['line']}  {f['value']}   cites: {', '.join(f['products'])}")
        print(f"        {f['context']}")

    if a.write_allowlist:
        ALLOWLIST.write_text(json.dumps(
            {f["key"]: {**allow.get(f["key"], {"reason": ""}),
                        "context": f["context"]}
             for f in findings}, indent=1, ensure_ascii=False))
        print(f"\n[check] wrote {ALLOWLIST.relative_to(REPO)} "
              f"({len(findings)} entries) — fill in `reason` for each")
        return 0
    if ungrounded:
        print(f"\n[check] {len(ungrounded)} number(s) appear in no product they cite. "
              "Fix the producer or the prose; use --write-allowlist only for numbers that "
              "are genuinely derived, and write down why.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
