// generated by build_demo_data.py — do not edit
window.DEMO_TASKS = ["130", "76", "17"];
window.CARBON = {
 "j_per_input_token": [
  0.05,
  0.4
 ],
 "j_per_output_token": [
  1.0,
  8.0
 ],
 "facility_factor": [
  1.23,
  1.97
 ],
 "grid_g_per_kwh": [
  131.0,
  144.0
 ],
 "region": "AWS eu-west-2 (London)",
 "boundary": "operational only (no embodied emissions); location-based grid factor"
};
window.DEMO = {
 "130": {
  "task": 130,
  "caption": "The answer is in the picture. The text tree never says \u201csunset\u201d.",
  "intent": "Navigate to the item on this page whose image is taken during a sunset.",
  "lanes": {
   "LOOK": {
    "success": true,
    "steps": 2,
    "cost": 0.0073,
    "seconds": 10.1,
    "tokens": 6501,
    "co2": [
     0.0229,
     0.3229
    ],
    "run": "B0_vision_classifieds_R24792_clean_replicate",
    "frames": [
     {
      "step": 0,
      "img": "frames/130/LOOK/000.png",
      "thought": "I need to identify the item whose image is taken during a sunset. Scanning the listings, the fourth item (bottom row, middle) shows a boat with a clear sunset in the background. I will click on this item to navigate to its detail page.",
      "action": "click",
      "ok": true,
      "mark": {
       "kind": "point",
       "x": 764.16,
       "y": 612.0
      },
      "cost_cum": 0.0037,
      "sec_cum": 5.7,
      "tok_cum": 3240,
      "co2_cum": [
       0.012,
       0.1686
      ]
     },
     {
      "step": 1,
      "img": "frames/130/LOOK/001.png",
      "thought": "",
      "action": "finish",
      "ok": true,
      "mark": null,
      "cost_cum": 0.0073,
      "sec_cum": 10.1,
      "tok_cum": 6501,
      "co2_cum": [
       0.0229,
       0.3229
      ]
     }
    ]
   },
   "READ": {
    "success": false,
    "steps": 9,
    "cost": 0.0412,
    "seconds": 57.5,
    "tokens": 37914,
    "co2": [
     0.1198,
     1.6867
    ],
    "run": "B0_dom_classifieds_R31194_clean_replicate",
    "frames": [
     {
      "step": 0,
      "img": "frames/130/READ/000.png",
      "thought": "I need to find an item whose image is taken during a sunset. The current page shows search results for 'banana boat'. I should scroll down to see more items and look for an image that might depict a sunset.",
      "action": "scroll",
      "ok": true,
      "mark": null,
      "cost_cum": 0.0042,
      "sec_cum": 6.7,
      "tok_cum": 3808,
      "co2_cum": [
       0.0126,
       0.1775
      ]
     },
     {
      "step": 1,
      "img": "frames/130/READ/001.png",
      "thought": "The current page shows boat listings with thumbnails. I need to find an item whose image was taken during a sunset. Since this is not evident from the small thumbnails, I should click on one of the listings to view its detailed page and check the image there. I will start by clicking on the first visible listing to inspect its image.",
      "action": "click",
      "ok": true,
      "mark": {
       "kind": "box",
       "x": 415.0,
       "y": 7.8125,
       "w": 203.296875,
       "h": 18.0,
       "id": 629
      },
      "cost_cum": 0.0097,
      "sec_cum": 13.0,
      "tok_cum": 8846,
      "co2_cum": [
       0.029,
       0.4088
      ]
     },
     {
      "step": 2,
      "img": "frames/130/READ/002.png",
      "thought": "I am currently on the item detail page for a boat, but the task is to find an item whose image was taken during a sunset. This item does not match the criteria, so I need to go back to the search results or previous page to continue searching for the correct item.",
      "action": "back",
      "ok": true,
      "mark": null,
      "cost_cum": 0.0134,
      "sec_cum": 20.2,
      "tok_cum": 12117,
      "co2_cum": [
       0.0406,
       0.5724
      ]
     },
     {
      "step": 3,
      "img": "frames/130/READ/003.png",
      "thought": "The current page shows a list of boats, but none of the visible items mention or depict a sunset. I need to scroll down to see more items and potentially find one with a sunset image.",
      "action": "scroll",
      "ok": true,
      "mark": null,
      "cost_cum": 0.0189,
      "sec_cum": 26.9,
      "tok_cum": 17264,
      "co2_cum": [
       0.056,
       0.7891
      ]
     },
     {
      "step": 4,
      "img": "frames/130/READ/004.png",
      "thought": "I need to find an item whose image is taken during a sunset. The current page shows boat listings with thumbnail images. I should scroll down to see more items and check if any of the images appear to be taken during sunset.",
      "action": "scroll",
      "ok": false,
      "mark": null,
      "cost_cum": 0.0236,
      "sec_cum": 33.5,
      "tok_cum": 21567,
      "co2_cum": [
       0.0698,
       0.9834
      ]
     },
     {
      "step": 5,
      "img": "frames/130/READ/005.png",
      "thought": "The current page shows a list of boats with thumbnail images, but none of the visible images appear to be taken during a sunset. I need to scroll down to see more items and potentially find an image that matches the sunset criteria.",
      "action": "scroll",
      "ok": false,
      "mark": null,
      "cost_cum": 0.0283,
      "sec_cum": 40.1,
      "tok_cum": 25912,
      "co2_cum": [
       0.0837,
       1.1791
      ]
     },
     {
      "step": 6,
      "img": "frames/130/READ/006.png",
      "thought": "",
      "action": "click",
      "ok": true,
      "mark": {
       "kind": "box",
       "x": 700.0,
       "y": 469.625,
       "w": 40.0,
       "h": 40.0,
       "id": 2729
      },
      "cost_cum": 0.0328,
      "sec_cum": 47.5,
      "tok_cum": 30243,
      "co2_cum": [
       0.0951,
       1.3401
      ]
     },
     {
      "step": 7,
      "img": "frames/130/READ/007.png",
      "thought": "I need to navigate to the item whose image is taken during a sunset. The first item, '16 Pontoon boat- new motor', is a potential candidate. I will click on it to view its details and check the image.",
      "action": "click",
      "ok": true,
      "mark": {
       "kind": "box",
       "x": 403.0,
       "y": 242.0,
       "w": 227.296875,
       "h": 190.40625,
       "id": 3314
      },
      "cost_cum": 0.0374,
      "sec_cum": 53.2,
      "tok_cum": 34416,
      "co2_cum": [
       0.1085,
       1.528
      ]
     },
     {
      "step": 8,
      "img": "frames/130/READ/008.png",
      "thought": "",
      "action": "finish",
      "ok": true,
      "mark": null,
      "cost_cum": 0.0412,
      "sec_cum": 57.5,
      "tok_cum": 37914,
      "co2_cum": [
       0.1198,
       1.6867
      ]
     }
    ]
   },
   "BOTH": {
    "success": true,
    "steps": 3,
    "cost": 0.014,
    "seconds": 31.5,
    "tokens": 13241,
    "co2": [
     0.0377,
     0.5305
    ],
    "run": "B0_som_classifieds_20260803_084743_413015398_3677519_R30696",
    "frames": [
     {
      "step": 0,
      "img": "frames/130/BOTH/000.png",
      "thought": "",
      "action": "click",
      "ok": true,
      "mark": {
       "kind": "box",
       "x": 652.296875,
       "y": 525.40625,
       "w": 227.296875,
       "h": 189.40625,
       "id": 53
      },
      "cost_cum": 0.005,
      "sec_cum": 6.5,
      "tok_cum": 4799,
      "co2_cum": [
       0.0124,
       0.1746
      ]
     },
     {
      "step": 1,
      "img": "frames/130/BOTH/001.png",
      "thought": "",
      "action": "click",
      "ok": true,
      "mark": {
       "kind": "box",
       "x": 150.0,
       "y": 353.0,
       "w": 550.0,
       "h": 412.5,
       "id": 17
      },
      "cost_cum": 0.0093,
      "sec_cum": 18.6,
      "tok_cum": 9011,
      "co2_cum": [
       0.0235,
       0.3307
      ]
     },
     {
      "step": 2,
      "img": "frames/130/BOTH/002.png",
      "thought": "The main image on the page (element_id=12) clearly shows a boat during sunset, which matches the task requirement. I have successfully navigated to the correct item.",
      "action": "finish",
      "ok": true,
      "mark": null,
      "cost_cum": 0.014,
      "sec_cum": 31.5,
      "tok_cum": 13241,
      "co2_cum": [
       0.0377,
       0.5305
      ]
     }
    ]
   }
  },
  "pick": {
   "mode": "dom",
   "source": "results/phantom_paper/l1_router_offline_20260715/router_offline_replay.json",
   "lane": "READ",
   "success": false
  }
 },
 "76": {
  "task": 76,
  "caption": "The answer is in the form. LOOK wanders 26 steps and never edits it.",
  "intent": "Navigate to my listing of the blue bike and change the price to $85.50 (including in the description).",
  "lanes": {
   "LOOK": {
    "success": false,
    "steps": 26,
    "cost": 0.1026,
    "seconds": 614.3,
    "tokens": 91909,
    "co2": [
     0.3193,
     4.4966
    ],
    "run": "B0_vision_classifieds_R24792_clean_replicate",
    "frames": [
     {
      "step": 0,
      "img": "frames/76/LOOK/000.png",
      "thought": "I need to navigate to my account to find my listings, including the blue bike, so I can edit its price. Clicking 'My account' is the logical first step to access my personal listings page.",
      "action": "click",
      "ok": true,
      "mark": {
       "kind": "point",
       "x": 880.64,
       "y": 42.48
      },
      "cost_cum": 0.0036,
      "sec_cum": 7.9,
      "tok_cum": 3228,
      "co2_cum": [
       0.0111,
       0.1556
      ]
     },
     {
      "step": 1,
      "img": "frames/76/LOOK/001.png",
      "thought": "I am on my listings page, but the blue bike listing is not visible. I need to scroll down to find it.",
      "action": "scroll",
      "ok": true,
      "mark": null,
      "cost_cum": 0.0072,
      "sec_cum": 15.8,
      "tok_cum": 6484,
      "co2_cum": [
       0.0216,
       0.3044
      ]
     },
     {
      "step": 2,
      "img": "frames/76/LOOK/002.png",
      "thought": "I need to locate the blue bike listing. The screenshot shows a 'Classic Road Bike - Lightweight Frame' with a bicycle image that appears blue. I will click the 'Edit item' button for this listing to proceed to edit the price.",
      "action": "click",
      "ok": true,
      "mark": {
       "kind": "point",
       "x": 545.28,
       "y": 349.92
      },
      "cost_cum": 0.0109,
      "sec_cum": 48.7,
      "tok_cum": 9802,
      "co2_cum": [
       0.0336,
       0.4731
      ]
     },
     {
      "step": 3,
      "img": "frames/76/LOOK/003.png",
      "thought": "I am on the edit page for the listing titled 'Classic Road Bike - Lightweight Frame'. The description contains the price $250, which I need to change to $85.50. I will first click into the description text area to edit the price.",
      "action": "click",
      "ok": false,
      "mark": {
       "kind": "point",
       "x": 640.0,
       "y": 504.0
      },
      "cost_cum": 0.0147,
      "sec_cum": 81.3,
      "tok_cum": 13172,
      "co2_cum": [
       0.046,
       0.6475
      ]
     },
     {
      "step": 4,
      "img": "frames/76/LOOK/004.png",
      "thought": "",
      "action": "type",
      "ok": true,
      "mark": {
       "kind": "point",
       "x": 638.72,
       "y": 504.0
      },
      "cost_cum": 0.0188,
      "sec_cum": 115.4,
      "tok_cum": 16628,
      "co2_cum": [
       0.0604,
       0.8511
      ]
     },
     {
      "step": 5,
      "img": "frames/76/LOOK/005.png",
      "thought": "I have successfully updated the description to include the price $85.50 as required. The next logical step is to publish the updated listing to complete the task.",
      "action": "click",
      "ok": true,
      "mark": {
       "kind": "point",
       "x": 1071.36,
       "y": 42.48
      },
      "cost_cum": 0.0227,
      "sec_cum": 120.7,
      "tok_cum": 20160,
      "co2_cum": [
       0.0722,
       1.0175
      ]
     },
     {
      "step": 6,
      "img": "frames/76/LOOK/006.png",
      "thought": "I am on the 'Publish a listing' page, which is not where I can edit my existing blue bike listing. I need to navigate back to my account or listings page to find and edit the specific item.",
      "action": "back",
      "ok": true,
      "mark": null,
      "cost_cum": 0.0266,
      "sec_cum": 153.3,
      "tok_cum": 23725,
      "co2_cum": [
       0.0839,
       1.182
      ]
     },
     {
      "step": 7,
      "img": "frames/76/LOOK/007.png",
      "thought": "I am on the edit page for the bike listing, and I can see that the description already includes the price $85.50. The task requires changing the price to $85.50, which is already done. I should now publish the listing to complete the task.",
      "action": "click",
      "ok": true,
      "mark": {
       "kind": "point",
       "x": 1071.36,
       "y": 42.48
      },
      "cost_cum": 0.0307,
      "sec_cum": 159.4,
      "tok_cum": 27355,
      "co2_cum": [
       0.097,
       1.3659
      ]
     },
     {
      "step": 8,
      "img": "frames/76/LOOK/008.png",
      "thought": "I am currently on the 'Publish a listing' page, which is not where I can edit my existing bike listing. I need to navigate back to my account or listings page to find and edit the specific blue bike listing.",
      "action": "back",
      "ok": true,
      "mark": null,
      "cost_cum": 0.0347,
      "sec_cum": 191.8,
      "tok_cum": 30997,
      "co2_cum": [
       0.1089,
       1.534
      ]
     },
     {
      "step": 9,
      "img": "frames/76/LOOK/009.png",
      "thought": "I am on the edit page for the listing. The description already contains the price $85.50 as required. I need to ensure the price is also set in the appropriate field (likely below the visible area) and then publish the listing. I will scroll down to find the price field and the publish button.",
      "action": "scroll",
      "ok": true,
      "mark": null,
      "cost_cum": 0.0389,
      "sec_cum": 224.5,
      "tok_cum": 34664,
      "co2_cum": [
       0.1221,
       1.7196
      ]
     },
     {
      "step": 10,
      "img": "frames/76/LOOK/010.png",
      "thought": "I need to change the price field from $250.00 to $85.50. The price input is visible at the top of the form, and typing into it should update the listing price.",
      "action": "type",
      "ok": true,
      "mark": {
       "kind": "point",
       "x": 537.6,
       "y": 45.36
      },
      "cost_cum": 0.043,
      "sec_cum": 257.9,
      "tok_cum": 38335,
      "co2_cum": [
       0.1352,
       1.9036
      ]
     },
     {
      "step": 11,
      "img": "frames/76/LOOK/011.png",
      "thought": "I have successfully changed the price to $85.50 as required. The task also mentioned updating the description, which I did earlier. I need to ensure the changes are saved, so I will scroll down to look for a save or submit button.",
      "action": "scroll",
      "ok": true,
      "mark": null,
      "cost_cum": 0.0471,
      "sec_cum": 290.0,
      "tok_cum": 41994,
      "co2_cum": [
       0.1478,
       2.0812
      ]
     },
     {
      "step": 12,
      "img": "frames/76/LOOK/012.png",
      "thought": "I need to navigate to my listing for the blue bike. Since I am currently on a form that seems to be for editing seller information or a listing, I should look for a way to go back to my listings or find a search function to locate the specific bike. The current page does not show any listing details or options to edit price or description directly.",
      "action": "scroll",
      "ok": true,
      "mark": null,
      "cost_cum": 0.0512,
      "sec_cum": 322.7,
      "tok_cum": 45671,
      "co2_cum": [
       0.1613,
       2.2714
      ]
     },
     {
      "step": 13,
      "img": "frames/76/LOOK/013.png",
      "thought": "I need to scroll further down the page to find the description field where I can update the price to $85.50. The current view only shows the price input and image upload sections, so scrolling is necessary to locate the description area.",
      "action": "scroll",
      "ok": true,
      "mark": null,
      "cost_cum": 0.0552,
      "sec_cum": 355.2,
      "tok_cum": 49223,
      "co2_cum": [
       0.1736,
       2.445
      ]
     },
     {
      "step": 14,
      "img": "frames/76/LOOK/014.png",
      "thought": "I need to find the price field on this page to update it to $85.50. Since I can't see it in the current view, I'll scroll up to look for it.",
      "action": "scroll",
      "ok": true,
      "mark": null,
      "cost_cum": 0.0591,
      "sec_cum": 387.9,
      "tok_cum": 52766,
      "co2_cum": [
       0.1855,
       2.6124
      ]
     },
     {
      "step": 15,
      "img": "frames/76/LOOK/015.png",
      "thought": "I need to ensure the price is set to $85.50 in the description as well. The current view shows the price field already set to 85.50, but I must locate and edit the description field to include this price. Since the description is not visible, I should scroll up to find it.",
      "action": "scroll",
      "ok": true,
      "mark": null,
      "cost_cum": 0.0632,
      "sec_cum": 420.0,
      "tok_cum": 56338,
      "co2_cum": [
       0.1985,
       2.7963
      ]
     },
     {
      "step": 16,
      "img": "frames/76/LOOK/016.png",
      "thought": "The price has been successfully updated to $85.50 in the description, and I am now on the edit listing page. The next logical step is to publish the updated listing to complete the task.",
      "action": "click",
      "ok": true,
      "mark": {
       "kind": "point",
       "x": 1072.64,
       "y": 41.76
      },
      "cost_cum": 0.0671,
      "sec_cum": 425.5,
      "tok_cum": 59892,
      "co2_cum": [
       0.2107,
       2.9682
      ]
     },
     {
      "step": 17,
      "img": "frames/76/LOOK/017.png",
      "thought": "I am currently on the 'Publish a listing' page, which is not where I can edit my existing blue bike listing. I need to navigate to my account or listings page to find and edit the existing item. The 'My account' link in the header is likely the correct path to access my listings.",
      "action": "click",
      "ok": true,
      "mark": {
       "kind": "point",
       "x": 880.64,
       "y": 41.76
      },
      "cost_cum": 0.0712,
      "sec_cum": 433.6,
      "tok_cum": 63473,
      "co2_cum": [
       0.224,
       3.1547
      ]
     },
     {
      "step": 18,
      "img": "frames/76/LOOK/018.png",
      "thought": "I need to find the listing for the blue bike. Since it is not visible in the current view, I should scroll down the page to look for it.",
      "action": "scroll",
      "ok": true,
      "mark": null,
      "cost_cum": 0.0751,
      "sec_cum": 441.4,
      "tok_cum": 67015,
      "co2_cum": [
       0.2355,
       3.3167
      ]
     },
     {
      "step": 19,
      "img": "frames/76/LOOK/019.png",
      "thought": "I need to edit the listing for the blue bike. I can see the 'Edit item' button for the bike listing, which is the next step to change the price and description.",
      "action": "click",
      "ok": true,
      "mark": {
       "kind": "point",
       "x": 540.16,
       "y": 345.6
      },
      "cost_cum": 0.079,
      "sec_cum": 474.3,
      "tok_cum": 70558,
      "co2_cum": [
       0.2475,
       3.4858
      ]
     },
     {
      "step": 20,
      "img": "frames/76/LOOK/020.png",
      "thought": "I need to scroll down to find the price field on this listing edit page, as it is not currently visible in the screenshot.",
      "action": "scroll",
      "ok": true,
      "mark": null,
      "cost_cum": 0.0828,
      "sec_cum": 506.6,
      "tok_cum": 74090,
      "co2_cum": [
       0.2587,
       3.6439
      ]
     },
     {
      "step": 21,
      "img": "frames/76/LOOK/021.png",
      "thought": "",
      "action": "type",
      "ok": true,
      "mark": {
       "kind": "point",
       "x": 540.16,
       "y": 43.92
      },
      "cost_cum": 0.0866,
      "sec_cum": 538.3,
      "tok_cum": 77602,
      "co2_cum": [
       0.269,
       3.7893
      ]
     },
     {
      "step": 22,
      "img": "frames/76/LOOK/022.png",
      "thought": "I need to scroll down to find the description field to update the price there as well. The current view shows the price and image sections, but the description is likely further down.",
      "action": "scroll",
      "ok": true,
      "mark": null,
      "cost_cum": 0.0905,
      "sec_cum": 570.3,
      "tok_cum": 81150,
      "co2_cum": [
       0.2808,
       3.9544
      ]
     },
     {
      "step": 23,
      "img": "frames/76/LOOK/023.png",
      "thought": "",
      "action": "type",
      "ok": true,
      "mark": {
       "kind": "point",
       "x": 540.16,
       "y": 390.96
      },
      "cost_cum": 0.0943,
      "sec_cum": 603.3,
      "tok_cum": 84681,
      "co2_cum": [
       0.2917,
       4.1089
      ]
     },
     {
      "step": 24,
      "img": "frames/76/LOOK/024.png",
      "thought": "The description field already contains the desired text including the updated price ($85.50). The next logical step is to save these changes by clicking the 'Update' button to finalize the edit.",
      "action": "click",
      "ok": true,
      "mark": {
       "kind": "point",
       "x": 426.24,
       "y": 495.36
      },
      "cost_cum": 0.0983,
      "sec_cum": 608.9,
      "tok_cum": 88258,
      "co2_cum": [
       0.3039,
       4.2809
      ]
     },
     {
      "step": 25,
      "img": "frames/76/LOOK/025.png",
      "thought": "The task was to navigate to my listing of the blue bike and change the price to $85.50 (including in the description). The screenshot confirms the price is now $85.50 and the description matches the required text. The green banner also states 'Great! We've just updated your listing', indicating the edit was successful. The task is complete.",
      "action": "finish",
      "ok": true,
      "mark": null,
      "cost_cum": 0.1026,
      "sec_cum": 614.3,
      "tok_cum": 91909,
      "co2_cum": [
       0.3193,
       4.4966
      ]
     }
    ]
   },
   "READ": {
    "success": true,
    "steps": 12,
    "cost": 0.0901,
    "seconds": 280.5,
    "tokens": 84228,
    "co2": [
     0.2506,
     3.5292
    ],
    "run": "B0_dom_classifieds_R31194_clean_replicate",
    "frames": [
     {
      "step": 0,
      "img": "frames/76/READ/000.png",
      "thought": "Since I need to navigate to my listing of the blue bike, I should first go to my account dashboard where my listings are likely managed.",
      "action": "click",
      "ok": true,
      "mark": {
       "kind": "box",
       "x": 829.0,
       "y": 26.0,
       "w": 110.0,
       "h": 35.0,
       "id": 115
      },
      "cost_cum": 0.0037,
      "sec_cum": 9.4,
      "tok_cum": 3343,
      "co2_cum": [
       0.011,
       0.1551
      ]
     },
     {
      "step": 1,
      "img": "frames/76/READ/001.png",
      "thought": "I need to find the blue bike listing. Since it's not visible on the current page, I should scroll down to see more listings.",
      "action": "scroll",
      "ok": true,
      "mark": null,
      "cost_cum": 0.0077,
      "sec_cum": 18.1,
      "tok_cum": 7014,
      "co2_cum": [
       0.0226,
       0.3187
      ]
     },
     {
      "step": 2,
      "img": "frames/76/READ/002.png",
      "thought": "I need to find the blue bike listing. The current page shows a 'Classic Road Bike - Lightweight Frame' which might be the one I'm looking for. I will click on this listing to view its details and confirm if it's the blue bike I want to edit.",
      "action": "click",
      "ok": true,
      "mark": {
       "kind": "box",
       "x": 507.0,
       "y": 188.0,
       "w": 280.0,
       "h": 22.0,
       "id": 1580
      },
      "cost_cum": 0.0118,
      "sec_cum": 24.2,
      "tok_cum": 10738,
      "co2_cum": [
       0.0353,
       0.4966
      ]
     },
     {
      "step": 3,
      "img": "frames/76/READ/003.png",
      "thought": "I am on the item detail page for the blue bike. To change the price, I need to edit the listing. The 'Edit item' link is visible and should take me to the edit page where I can update the price and description.",
      "action": "click",
      "ok": true,
      "mark": {
       "kind": "box",
       "x": 155.0,
       "y": 338.0,
       "w": 63.0,
       "h": 20.0,
       "id": 2322
      },
      "cost_cum": 0.0155,
      "sec_cum": 60.3,
      "tok_cum": 14015,
      "co2_cum": [
       0.0471,
       0.6627
      ]
     },
     {
      "step": 4,
      "img": "frames/76/READ/004.png",
      "thought": "",
      "action": "type",
      "ok": false,
      "mark": {
       "kind": "box",
       "x": 378.0,
       "y": 338.0,
       "w": 532.0,
       "h": 50.0,
       "id": 2969
      },
      "cost_cum": 0.0196,
      "sec_cum": 97.3,
      "tok_cum": 17282,
      "co2_cum": [
       0.0629,
       0.8861
      ]
     },
     {
      "step": 5,
      "img": "frames/76/READ/005.png",
      "thought": "The task requires changing the price to $85.50, which includes updating the description. The description field is visible and contains the current price of $250. I need to edit this text to replace $250 with $85.50.",
      "action": "type",
      "ok": true,
      "mark": {
       "kind": "box",
       "x": 378.0,
       "y": 403.0,
       "w": 532.0,
       "h": 300.0,
       "id": 2980
      },
      "cost_cum": 0.0242,
      "sec_cum": 132.8,
      "tok_cum": 20704,
      "co2_cum": [
       0.0839,
       1.1814
      ]
     },
     {
      "step": 6,
      "img": "frames/76/READ/006.png",
      "thought": "",
      "action": "wait",
      "ok": false,
      "mark": null,
      "cost_cum": 0.0285,
      "sec_cum": 167.9,
      "tok_cum": 24151,
      "co2_cum": [
       0.0998,
       1.4062
      ]
     },
     {
      "step": 7,
      "img": "frames/76/READ/007.png",
      "thought": "I need to locate the price field to update it to $85.50. Since the price is not visible in the current view, I should scroll down to reveal more fields, including the price input.",
      "action": "scroll",
      "ok": true,
      "mark": null,
      "cost_cum": 0.0322,
      "sec_cum": 204.7,
      "tok_cum": 27532,
      "co2_cum": [
       0.1114,
       1.5697
      ]
     },
     {
      "step": 8,
      "img": "frames/76/READ/008.png",
      "thought": "",
      "action": "type",
      "ok": true,
      "mark": {
       "kind": "box",
       "x": 378.0,
       "y": 23.0,
       "w": 345.796875,
       "h": 50.0,
       "id": 2992
      },
      "cost_cum": 0.0502,
      "sec_cum": 237.3,
      "tok_cum": 45300,
      "co2_cum": [
       0.1534,
       2.1609
      ]
     },
     {
      "step": 9,
      "img": "frames/76/READ/009.png",
      "thought": "I have successfully navigated to the edit page for the blue bike listing. I've already updated the price to $85.50 and included the price in the description. Now, I need to ensure these changes are saved by submitting the form. The next logical step is to look for a 'Save' or 'Update' button to finalize the changes.",
      "action": "scroll",
      "ok": true,
      "mark": null,
      "cost_cum": 0.0686,
      "sec_cum": 270.6,
      "tok_cum": 63151,
      "co2_cum": [
       0.1987,
       2.799
      ]
     },
     {
      "step": 10,
      "img": "frames/76/READ/010.png",
      "thought": "",
      "action": "click",
      "ok": true,
      "mark": {
       "kind": "box",
       "x": 378.0,
       "y": 470.0,
       "w": 100.0,
       "h": 50.0,
       "id": 8264
      },
      "cost_cum": 0.0863,
      "sec_cum": 276.5,
      "tok_cum": 80691,
      "co2_cum": [
       0.24,
       3.3806
      ]
     },
     {
      "step": 11,
      "img": "frames/76/READ/011.png",
      "thought": "",
      "action": "finish",
      "ok": true,
      "mark": null,
      "cost_cum": 0.0901,
      "sec_cum": 280.5,
      "tok_cum": 84228,
      "co2_cum": [
       0.2506,
       3.5292
      ]
     }
    ]
   },
   "BOTH": {
    "success": false,
    "steps": 7,
    "cost": 0.0628,
    "seconds": 189.3,
    "tokens": 59992,
    "co2": [
     0.1643,
     2.3138
    ],
    "run": "B0_som_classifieds_20260803_084743_413015398_3677519_R30696",
    "frames": [
     {
      "step": 0,
      "img": "frames/76/BOTH/000.png",
      "thought": "Since I need to find my own listing for the blue bike, I should navigate to my account dashboard where my listings are likely displayed. Clicking 'My account' is the logical first step.",
      "action": "click",
      "ok": true,
      "mark": {
       "kind": "box",
       "x": 829.0,
       "y": 26.0,
       "w": 110.0,
       "h": 35.0,
       "id": 4
      },
      "cost_cum": 0.0048,
      "sec_cum": 9.3,
      "tok_cum": 4441,
      "co2_cum": [
       0.0139,
       0.1951
      ]
     },
     {
      "step": 1,
      "img": "frames/76/BOTH/001.png",
      "thought": "I need to find the listing for the blue bike. Since it's not visible on the current page, I should scroll down to see more listings.",
      "action": "scroll",
      "ok": true,
      "mark": null,
      "cost_cum": 0.0098,
      "sec_cum": 19.3,
      "tok_cum": 9119,
      "co2_cum": [
       0.0278,
       0.3916
      ]
     },
     {
      "step": 2,
      "img": "frames/76/BOTH/002.png",
      "thought": "I need to navigate to the listing for the blue bike. The listing titled 'Classic Road Bike - Lightweight Frame' appears to be the correct item based on the description and image. I will click on the 'Edit item' link for this listing to proceed with changing the price.",
      "action": "click",
      "ok": true,
      "mark": {
       "kind": "box",
       "x": 507.0,
       "y": 337.0,
       "w": 67.0,
       "h": 26.0,
       "id": 23
      },
      "cost_cum": 0.015,
      "sec_cum": 53.8,
      "tok_cum": 13850,
      "co2_cum": [
       0.0431,
       0.6066
      ]
     },
     {
      "step": 3,
      "img": "frames/76/BOTH/003.png",
      "thought": "",
      "action": "type",
      "ok": true,
      "mark": {
       "kind": "box",
       "x": 378.0,
       "y": 403.0,
       "w": 532.0,
       "h": 300.0,
       "id": 20
      },
      "cost_cum": 0.0198,
      "sec_cum": 88.3,
      "tok_cum": 18087,
      "co2_cum": [
       0.0589,
       0.8294
      ]
     },
     {
      "step": 4,
      "img": "frames/76/BOTH/004.png",
      "thought": "The price has been updated in the description, but I need to ensure the listing is fully published or saved. Scrolling down may reveal a 'Save' or 'Publish' button to finalize the changes.",
      "action": "scroll",
      "ok": true,
      "mark": null,
      "cost_cum": 0.0245,
      "sec_cum": 121.2,
      "tok_cum": 22406,
      "co2_cum": [
       0.0721,
       1.0159
      ]
     },
     {
      "step": 5,
      "img": "frames/76/BOTH/005.png",
      "thought": "The price field is currently showing 250.00, and I need to change it to 85.50. The price input field is clearly identified as element [id=3] in the SOM_MARKS list. I will type the new price into this field.",
      "action": "type",
      "ok": true,
      "mark": {
       "kind": "box",
       "x": 378.0,
       "y": 23.0,
       "w": 345.796875,
       "h": 50.0,
       "id": 3
      },
      "cost_cum": 0.0438,
      "sec_cum": 157.2,
      "tok_cum": 41205,
      "co2_cum": [
       0.1194,
       1.6821
      ]
     },
     {
      "step": 6,
      "img": "frames/76/BOTH/006.png",
      "thought": "",
      "action": "finish",
      "ok": true,
      "mark": null,
      "cost_cum": 0.0628,
      "sec_cum": 189.3,
      "tok_cum": 59992,
      "co2_cum": [
       0.1643,
       2.3138
      ]
     }
    ]
   }
  },
  "pick": {
   "mode": "dom",
   "source": "results/phantom_paper/l1_router_offline_20260715/router_offline_replay.json",
   "lane": "READ",
   "success": true
  }
 },
 "17": {
  "task": 17,
  "caption": "Red handlebars must be seen; $900\u2013950 must be filtered. Neither alone is enough.",
  "intent": "Show me the cheapest bike with red handlebars between $900-950.",
  "lanes": {
   "LOOK": {
    "success": false,
    "steps": 9,
    "cost": 0.0335,
    "seconds": 72.1,
    "tokens": 30436,
    "co2": [
     0.1009,
     1.4205
    ],
    "run": "B0_vision_classifieds_R24792_clean_replicate",
    "frames": [
     {
      "step": 0,
      "img": "frames/17/LOOK/000.png",
      "thought": "",
      "action": "type",
      "ok": true,
      "mark": {
       "kind": "point",
       "x": 384.0,
       "y": 300.24
      },
      "cost_cum": 0.0034,
      "sec_cum": 7.8,
      "tok_cum": 3183,
      "co2_cum": [
       0.0093,
       0.1309
      ]
     },
     {
      "step": 1,
      "img": "frames/17/LOOK/001.png",
      "thought": "I have entered 'bike' in the keyword field. To proceed with finding the cheapest bike with red handlebars between $900-950, I need to execute the search to see the results and apply further filters or sorting.",
      "action": "click",
      "ok": true,
      "mark": {
       "kind": "point",
       "x": 1024.0,
       "y": 299.52
      },
      "cost_cum": 0.0071,
      "sec_cum": 16.9,
      "tok_cum": 6451,
      "co2_cum": [
       0.0212,
       0.298
      ]
     },
     {
      "step": 2,
      "img": "frames/17/LOOK/002.png",
      "thought": "",
      "action": "type",
      "ok": true,
      "mark": {
       "kind": "point",
       "x": 197.12,
       "y": 432.0
      },
      "cost_cum": 0.0105,
      "sec_cum": 26.1,
      "tok_cum": 9705,
      "co2_cum": [
       0.0307,
       0.4323
      ]
     },
     {
      "step": 3,
      "img": "frames/17/LOOK/003.png",
      "thought": "I need to set the maximum price to 950 in the 'Max.' input field to narrow the search for bikes between $900 and $950.",
      "action": "type",
      "ok": true,
      "mark": {
       "kind": "point",
       "x": 305.92,
       "y": 434.16
      },
      "cost_cum": 0.0143,
      "sec_cum": 35.6,
      "tok_cum": 13045,
      "co2_cum": [
       0.0425,
       0.5992
      ]
     },
     {
      "step": 4,
      "img": "frames/17/LOOK/004.png",
      "thought": "I need to apply the price filter to see only bikes priced between $900 and $950. Clicking the 'Apply' button will update the listings to match the specified price range.",
      "action": "click",
      "ok": true,
      "mark": {
       "kind": "point",
       "x": 202.24,
       "y": 491.04
      },
      "cost_cum": 0.0181,
      "sec_cum": 44.5,
      "tok_cum": 16426,
      "co2_cum": [
       0.0541,
       0.7621
      ]
     },
     {
      "step": 5,
      "img": "frames/17/LOOK/005.png",
      "thought": "",
      "action": "select_option",
      "ok": true,
      "mark": {
       "kind": "point",
       "x": 990.72,
       "y": 160.56
      },
      "cost_cum": 0.0217,
      "sec_cum": 53.0,
      "tok_cum": 19829,
      "co2_cum": [
       0.0643,
       0.9059
      ]
     },
     {
      "step": 6,
      "img": "frames/17/LOOK/006.png",
      "thought": "I need to scroll down to check for more listings or details about the bikes, particularly looking for any mention of red handlebars in the descriptions or images.",
      "action": "scroll",
      "ok": true,
      "mark": null,
      "cost_cum": 0.0255,
      "sec_cum": 61.8,
      "tok_cum": 23301,
      "co2_cum": [
       0.0756,
       1.065
      ]
     },
     {
      "step": 7,
      "img": "frames/17/LOOK/007.png",
      "thought": "I need to open the listing for the Two Cannondale bikes to check if it has red handlebars, as this is the cheapest bike listed in the $900-950 range. I will click the title to view the item details and confirm the handlebar color.",
      "action": "click",
      "ok": true,
      "mark": {
       "kind": "point",
       "x": 581.12,
       "y": 409.68
      },
      "cost_cum": 0.0295,
      "sec_cum": 67.4,
      "tok_cum": 26855,
      "co2_cum": [
       0.0885,
       1.2471
      ]
     },
     {
      "step": 8,
      "img": "frames/17/LOOK/008.png",
      "thought": "",
      "action": "finish",
      "ok": true,
      "mark": null,
      "cost_cum": 0.0335,
      "sec_cum": 72.1,
      "tok_cum": 30436,
      "co2_cum": [
       0.1009,
       1.4205
      ]
     }
    ]
   },
   "READ": {
    "success": false,
    "steps": 8,
    "cost": 0.0341,
    "seconds": 53.5,
    "tokens": 30379,
    "co2": [
     0.1072,
     1.5097
    ],
    "run": "B0_dom_classifieds_R31194_clean_replicate",
    "frames": [
     {
      "step": 0,
      "img": "frames/17/READ/000.png",
      "thought": "I need to search for bikes with red handlebars in the price range $900-950. First, I'll select the 'Bikes' category from the dropdown to narrow down the search.",
      "action": "select_option",
      "ok": true,
      "mark": {
       "kind": "box",
       "x": 640.0,
       "y": 278.0,
       "w": 274.0,
       "h": 50.0,
       "id": 148
      },
      "cost_cum": 0.0038,
      "sec_cum": 8.3,
      "tok_cum": 3362,
      "co2_cum": [
       0.0121,
       0.1701
      ]
     },
     {
      "step": 1,
      "img": "frames/17/READ/001.png",
      "thought": "I need to search for bikes with red handlebars in the $900-950 range. The search bar is visible, so I will start by entering the search term 'red handlebars' to narrow down the results.",
      "action": "type",
      "ok": true,
      "mark": {
       "kind": "box",
       "x": 150.0,
       "y": 278.0,
       "w": 470.0,
       "h": 50.0,
       "id": 140
      },
      "cost_cum": 0.0076,
      "sec_cum": 17.2,
      "tok_cum": 6761,
      "co2_cum": [
       0.0244,
       0.3443
      ]
     },
     {
      "step": 2,
      "img": "frames/17/READ/002.png",
      "thought": "I need to set the minimum price to $900 to filter the results within the desired range.",
      "action": "type",
      "ok": true,
      "mark": {
       "kind": "box",
       "x": 162.0,
       "y": 412.0,
       "w": 87.0,
       "h": 40.0,
       "id": 1425
      },
      "cost_cum": 0.0118,
      "sec_cum": 25.4,
      "tok_cum": 10600,
      "co2_cum": [
       0.0366,
       0.5162
      ]
     },
     {
      "step": 3,
      "img": "frames/17/READ/003.png",
      "thought": "I need to set the maximum price to 950 to narrow the search results to bikes within the $900-950 range. The max price field is currently empty, so I will type '950' into it.",
      "action": "type",
      "ok": true,
      "mark": {
       "kind": "box",
       "x": 261.0,
       "y": 412.0,
       "w": 87.0,
       "h": 40.0,
       "id": 1433
      },
      "cost_cum": 0.0162,
      "sec_cum": 31.7,
      "tok_cum": 14529,
      "co2_cum": [
       0.0503,
       0.7089
      ]
     },
     {
      "step": 4,
      "img": "frames/17/READ/004.png",
      "thought": "I need to sort the results by 'Lower price first' to ensure I see the cheapest bike first. The current sort is 'Newly listed', so I will change it.",
      "action": "select_option",
      "ok": true,
      "mark": {
       "kind": "box",
       "x": 1021.0,
       "y": 227.0,
       "w": 85.0,
       "h": 19.0,
       "id": 2506
      },
      "cost_cum": 0.0207,
      "sec_cum": 37.2,
      "tok_cum": 18582,
      "co2_cum": [
       0.0638,
       0.8983
      ]
     },
     {
      "step": 5,
      "img": "frames/17/READ/005.png",
      "thought": "The cheapest bike with red handlebars in the $900-950 range is the '2023 Specialized Mountain Bike' listed at $900.00. I need to click on this listing to view its details as per the task requirement.",
      "action": "click",
      "ok": false,
      "mark": {
       "kind": "box",
       "x": 507.0,
       "y": 333.0,
       "w": 623.0,
       "h": 139.0,
       "id": 3068
      },
      "cost_cum": 0.0252,
      "sec_cum": 42.2,
      "tok_cum": 22683,
      "co2_cum": [
       0.0778,
       1.0953
      ]
     },
     {
      "step": 6,
      "img": "frames/17/READ/006.png",
      "thought": "The task is to show the cheapest bike with red handlebars between $900-950. The first listing, '2023 Specialized Mountain Bike', is priced at $900 and matches the criteria. I should open its detail page to confirm it has red handlebars.",
      "action": "click",
      "ok": true,
      "mark": {
       "kind": "box",
       "x": 507.0,
       "y": 333.0,
       "w": 233.0,
       "h": 22.0,
       "id": 3072
      },
      "cost_cum": 0.0299,
      "sec_cum": 48.3,
      "tok_cum": 26838,
      "co2_cum": [
       0.0921,
       1.2969
      ]
     },
     {
      "step": 7,
      "img": "frames/17/READ/007.png",
      "thought": "I have successfully navigated to the detail page of a bike that matches the criteria: it has red handlebars (implied by the search), is priced at $900, and falls within the $900-950 range. This appears to be the cheapest option available based on the previous sorting by price ascending. The task is now complete.",
      "action": "finish",
      "ok": true,
      "mark": null,
      "cost_cum": 0.0341,
      "sec_cum": 53.5,
      "tok_cum": 30379,
      "co2_cum": [
       0.1072,
       1.5097
      ]
     }
    ]
   },
   "BOTH": {
    "success": true,
    "steps": 6,
    "cost": 0.0314,
    "seconds": 74.3,
    "tokens": 29177,
    "co2": [
     0.089,
     1.2538
    ],
    "run": "B0_som_classifieds_20260803_084743_413015398_3677519_R30696",
    "frames": [
     {
      "step": 0,
      "img": "frames/17/BOTH/000.png",
      "thought": "",
      "action": "type",
      "ok": true,
      "mark": {
       "kind": "box",
       "x": 150.0,
       "y": 278.0,
       "w": 470.0,
       "h": 50.0,
       "id": 9
      },
      "cost_cum": 0.0046,
      "sec_cum": 18.2,
      "tok_cum": 4392,
      "co2_cum": [
       0.0119,
       0.1678
      ]
     },
     {
      "step": 1,
      "img": "frames/17/BOTH/001.png",
      "thought": "I need to filter the search results to show only bikes with red handlebars priced between $900 and $950. I will start by entering 900 in the 'Min.' price field.",
      "action": "type",
      "ok": true,
      "mark": {
       "kind": "box",
       "x": 162.0,
       "y": 412.0,
       "w": 87.0,
       "h": 40.0,
       "id": 24
      },
      "cost_cum": 0.0098,
      "sec_cum": 34.1,
      "tok_cum": 9221,
      "co2_cum": [
       0.0273,
       0.3841
      ]
     },
     {
      "step": 2,
      "img": "frames/17/BOTH/002.png",
      "thought": "I need to set the maximum price to 950 to narrow the search for bikes between $900 and $950. The max price input field is visible and ready for input.",
      "action": "type",
      "ok": true,
      "mark": {
       "kind": "box",
       "x": 261.0,
       "y": 412.0,
       "w": 87.0,
       "h": 40.0,
       "id": 27
      },
      "cost_cum": 0.0153,
      "sec_cum": 45.0,
      "tok_cum": 14309,
      "co2_cum": [
       0.0431,
       0.6067
      ]
     },
     {
      "step": 3,
      "img": "frames/17/BOTH/003.png",
      "thought": "The current sort order is 'Newly listed', but I need to find the cheapest bike. I will change the sort order to 'Lower price first' to ensure the least expensive options are shown at the top.",
      "action": "select_option",
      "ok": true,
      "mark": {
       "kind": "box",
       "x": 1021.0,
       "y": 155.0,
       "w": 85.0,
       "h": 19.0,
       "id": 36
      },
      "cost_cum": 0.021,
      "sec_cum": 63.4,
      "tok_cum": 19505,
      "co2_cum": [
       0.0593,
       0.8352
      ]
     },
     {
      "step": 4,
      "img": "frames/17/BOTH/004.png",
      "thought": "",
      "action": "click",
      "ok": true,
      "mark": {
       "kind": "box",
       "x": 402.0,
       "y": 261.0,
       "w": 95.0,
       "h": 79.15625,
       "id": 40
      },
      "cost_cum": 0.0263,
      "sec_cum": 69.0,
      "tok_cum": 24675,
      "co2_cum": [
       0.0725,
       1.0215
      ]
     },
     {
      "step": 5,
      "img": "frames/17/BOTH/005.png",
      "thought": "I have successfully navigated to the listing for the Cannondale Six13 Road Bike, which matches the criteria: red handlebars, price $900, within the $900\u2013950 range. This is the cheapest bike meeting the requirements as per the search results. The task is complete.",
      "action": "finish",
      "ok": true,
      "mark": null,
      "cost_cum": 0.0314,
      "sec_cum": 74.3,
      "tok_cum": 29177,
      "co2_cum": [
       0.089,
       1.2538
      ]
     }
    ]
   }
  },
  "pick": {
   "mode": "phantom_prompt",
   "source": "results/phantom_paper/l1_router_offline_20260715/router_offline_replay.json",
   "lane": null,
   "name": "text tree, read with the marked-screenshot instructions",
   "runs": [
    {
     "run": "B0_phantom_prompt_classifieds_20260528_040546_107246795_987141_R14655",
     "success": true,
     "steps": 9
    },
    {
     "run": "B0_phantom_prompt_classifieds_20260817_184335_813828144_2037698_R12207",
     "success": false,
     "steps": 7
    }
   ]
  }
 }
};
